name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        # Kommentar: Holt den Code aus dem Repository.

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        # Kommentar: Stellt sicher, dass die korrekte Node.js-Version installiert ist.

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        # Kommentar: Installiert Abhängigkeiten mit npm ci für konsistente Builds.

      # Run linter
      - name: Run linter
        run: npm run lint
        # Kommentar: Überprüft den Code mit einem Linter auf Fehler und Formatierungsprobleme.

      # Build project
      - name: Build project
        run: npm run build
        # Kommentar: Führt den Build-Prozess für Next.js aus.

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next
        # Kommentar: Veröffentlicht das gebaute Projekt im `.next`-Verzeichnis auf GitHub Pages.

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
