name: CI Workflow for Todo App

on:
  push:
    branches:
      - main

jobs:
  # Task 1: Build and Store Artifacts
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21' # Compatible with Next.js 15 and React 18

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: list files
        run: ls -la

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./next/
          retention-days: 30
          overwrite: true
          compression-level: 0

  # Task 2: Linting Job
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  # Task 3: Testing Job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Run tests
        run: npm test

  # Task 4: Deployment Simulation Job
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Simulate Deployment
        run: echo "Deployment successful"
