name: CI Workflow for Todo App

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the "main" branch.

jobs:
  # Task 1: Cache and Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Check out the code from the repository.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
        # Set up Node.js version 21, as required by the project.

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
        # Cache the Node.js modules (node_modules) to speed up dependency installation.

      - name: Install dependencies
        run: npm ci
        # Install dependencies using a clean install to ensure consistency.

      - name: Cache .next folder
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-
        # Cache the `.next` folder to reuse the build output in subsequent steps.

      - name: Build application
        run: npm run build
        # Build the application using the `npm run build` command.

      - name: Cache `out` folder
        uses: actions/cache@v3
        with:
          path: out
          key: ${{ runner.os }}-out-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-out-
        # Cache the `out` folder containing the static files for deployment.

      - name: Verify export output
        run: ls -la ./out
        # Verify that the `out` folder was created successfully.

  # Task 2: Linting
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  # Task 3: Testing
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # Task 4: Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore `out` folder cache
        uses: actions/cache@v3
        with:
          path: out
          key: ${{ runner.os }}-out-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-out-
        # Restore the cached `out` folder to deploy the prebuilt static files.

      - name: Verify export output before deploy
        run: ls -la ./out
        # Verify that the `out` folder exists before deployment.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          force_orphan: true
        # Deploy the static files from the `out` directory to GitHub Pages.
