name: CI Workflow for Shopping-List App

on:
  push:
    branches:
      - main

jobs:
  # Task 1: Initial Setup Job
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Updated Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  # Task 2: Linting Job
  lint:
    runs-on: ubuntu-latest
    needs: setup  # Runs after setup job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Updated Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  # Task 2: Testing Job
  test:
    runs-on: ubuntu-latest
    needs: lint  # Runs after lint job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Updated Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Task 3: Deployment Simulation Job
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Runs after test job completes successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Simulate Deployment
        run: echo "Deployment successful"
